# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-25 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.CharField(max_length=264, unique=True)),
                ('date', models.DateField()),
                ('comp_name', models.CharField(max_length=264)),
                ('command', models.CharField(max_length=264)),
            ],
        ),
    ]
